schoolstoreproject/schoolstoreproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('storeapp.urls')),
    path('', include('credential.urls')),
    path('department/', include('department.urls')),




]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

schoolstoreproject/storeapp/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('add',views.Orderview.as_view(),name="add"),
    path('', views.demo,name='demo'),
    path('home',views.home,name='home'),
    path('ajax/load-courses/', views.load_courses, name='ajax_load_courses'),
    # path('home/<int:pk>', views.order_update_view, name='order_change')
    # path('order',views.add_order,name='order'),
    # path('ajax/load_courses/', views.load_courses, name='ajax_load_courses'),
    # path('orders',views.update,name="don")

    ]

schoolstoreproject/storeapp/models.py
from django.db import models

# Create your models here.
from django.db import models
from department.models import Department, Course


# Create your models here.
class Purpose(models.Model):
    purpose = models.CharField(max_length=250)

    def __str__(self):
        return self.purpose


class Materials(models.Model):
    material = models.CharField(max_length=100)

    def __str__(self):
        return self.material


class Order(models.Model):
    name = models.CharField(max_length=100)
    dob = models.DateField()
    age = models.IntegerField()
    options=(
        ('male','male'),
        ('female','female')
    )
    gender = models.CharField(max_length=200,choices=options,default='male')
    phonenumber = models.CharField(max_length=10)
    mailid = models.EmailField(max_length=100)
    address = models.CharField(max_length=250)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True, blank=True)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True, blank=True)
    purpose = models.ForeignKey(Purpose, on_delete=models.CASCADE)
    materials = models.ManyToManyField(Materials)
    


    def __str__(self):
        return self.name
    

schoolstoreproject/templates/add.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <title>Dependent Dropdown in Django</title>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
    
                
            
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded"
                    href="#">Hii {{user.username}}</a></li>
    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded"
                    href="logout">Logout</a></li>
    
            </ul>
          
        </div>
    </nav>

<section class="page-section portfolio" id="portfolio">
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card border-0 shadow rounded-3 my-5">
                   <div class="card-body p-4 p-sm-5">
                        <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Fill the form!</p>
                        <div class="divider-custom">
                            <div class="row">
                                <div class="col-12">
                                    

                                    <form method="post" id="personForm" enctype="multipart/form-data" data-courses-url="{% url 'ajax_load_courses' %}">
                                        {% csrf_token %}
                                        {{ form.as_p }}
                                    <div class="d-grid">
                                        <button class="btn btn-primary btn-login text-uppercase fw-bold" type="submit">submit</button>
                                    </div>
                                    </form>

                                    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                                    <script>
                                        $("#id_department").change(function () {
                                            const url = $("#personForm").attr("data-courses-url"); 
                                            const departmentId = $(this).val();  

                                            $.ajax({                       
                                                url: url,                    
                                                data: {
                                                    'department_id': departmentId       
                                                },
                                                success: function (data) {   
                                                    $("#id_course").html(data);  
                                                    console.log(data);
                                                }
                                                
                                            });

                                        });
                                    </script>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% for m in messages %}
                <button type="button" class="btn btn-success">{{m}}</button>
                
                <div>
                    <button class="btn btn-info"
                    type="button"><a href="home">Home</a>
            </button>
                </div>
                {% endfor %}
              

            </div>
          
        </div>
    </div>
</section>

   
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">@copy; College of Engineering.All rights Reserved</p>
  </div>
<!-- Portfoli

</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>



<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
<!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</html>

schoolstoreproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
     <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">


<!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}"  crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/custom.css' %}">
    <script src="https://kit.fontawesome.com/34aaf61378.js" crossorigin="anonymous"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}

        {% endblock %}</title>
    <h1><center>College Store</center></h1>
</head>
<body>
<div class="container">
    {% include 'navbar.html' %}
    {% include 'header.html' %}

    {% block content %}
    {% endblock %}

</div>

{% include 'footer.html' %}



<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="{% static '/js/popper.min.js' %}" ></script>
<script src="{% static '/js/bootstrap.min.js' %}"></script>

</body>
</html>

schoolstoreproject/templates/drop.html
<option value="">---------</option>
{% for course in courses %}
<option value="{{ course.pk }}">{{ course.name }}</option>
{% endfor %}

schoolstoreproject/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Freelancer - Start Bootstrap Theme</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet"
          type="text/css"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>

</head>
<body id="page-top">
<!-- Navigation-->
<style>
    .banner{
 background-color:beige;
 width: 100%;
 height: 100px;

}

.banner-text{
 left:40%;
 position:absolute;
 transform:transform;
 

}
</style>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <dic class="banner-text">
                    <h1>College Store App</h1>
                </dic>
            </div>
        </div>
    </div>
</div>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item dropdown {% if 'department' in request.path %} active {% endif %} ">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Department
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% for d in links %}
                   <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/{{d.name}}">{{d.name}}</a></li>
                   {% endfor %}

               </ul>
            </li>
        
            <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded"
                                             href="/register">Register</a></li>
            <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded"
                                             href="/login">Login</a></li>          
        </ul>
      
    </div>
</nav>

<!-- Masthead-->
<header class="text-white text-center" style="background-color: beige;">
    <div class="container d-flex align-items-center flex-column">
        <!-- Masthead Avatar Image-->
        <img class="masthead-avatar mb-5" src="https://png.pngtree.com/png-clipart/20230405/original/pngtree-scool-college-logo-victor-png-image_9026968.png" alt="..."/>
        <!-- Masthead Heading-->
     
</header>
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">@copy; College of Engineering.All rights Reserved</p>
  </div>
<!-- Portfolio Section-->

<!-- Footer-->

<!-- Copyright Section-->

<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'js/scripts.js' %}"></script>
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<!-- * *                               SB Forms JS                               * *-->
<!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

schoolstoreproject/templates/login.html
<!DOCTYPE html>
<html lang="en">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>




<body>

  <div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card border-0 shadow rounded-3 my-5">
          <div class="card-body p-4 p-sm-5">
            <h5 class="card-title text-center mb-5 fw-light fs-5" style="font-family: Arial, Helvetica, sans-serif;">Sign In</h5>
            <form action="login" method="post">
                 {% csrf_token %}
              <div class="form-floating mb-3">
                 <input type="text"  class="form-control" name="username" />
                      <label class="form-label" >Username</label>
              </div>
              <div class="form-floating mb-3">
                 <input type="password"  class="form-control" name="password" />
                      <label class="form-label" >Password</label>
              </div>


              <div class="d-grid">
                <button class="btn btn-primary btn-login text-uppercase fw-bold" type="submit">Sign
                  in</button>
              </div>


            </form>

          </div>
        </div>
              {% for m in messages %}
              <h2>{{m}}</h2>

            {% endfor %}
      </div>
    </div>
  </div>
</body>

schoolstoreproject/templates/navbar.html
<!--<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item dropdown {% if 'department' in request.path %} active {% endif %} ">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Department
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% for d in links %}
                   <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/{{d.name}}">{{d.name}}</a></li>
                   {% endfor %}

               </ul>
            </li>
        
            <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded"
                                             href="/register">Register</a></li>
            <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded"
                                             href="/login">Login</a></li>          
        </ul>
      
    </div>
</nav>

schoolstoreproject/templates/order.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Freelancer - Start Bootstrap Theme</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet"
          type="text/css"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>

</head>
<body id="page-top">
<!-- Navigation-->
<style>
    .banner{
 background-color:beige;
 width: 100%;
 height: 100px;

}

.banner-text{
 left:4
 0%;
 position:absolute;
 transform:transform;
 

}
</style>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <dic class="banner-text">
                    <h1>College Store App</h1>
                </dic>
            </div>
        </div>
    </div>
</div>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            
        
            <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded"
                href="#">Hii {{user.username}}</a></li>
<li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded"
                href="logout">Logout</a></li>

        </ul>
      
    </div>
</nav>

<!-- Masthead-->
<div class="divider-custom">
    <div class="divider-custom-line"></div>
    <div class="divider-custom-icon"><a class="btn btn-outline-primary" href="/add" role="button">click here</a></div>
    <div class="divider-custom-line"></div>
</div>

<!-- Portfolio Section-->

<!-- Footer-->

<!-- Copyright Section-->

<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'js/scripts.js' %}"></script>
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<!-- * *                               SB Forms JS                               * *-->
<!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

schoolstoreproject/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
            crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>

<section class="vh-100" style="background-color: #eee;">
    <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-12 col-xl-11">
                <div class="card text-black" style="border-radius: 25px;">
                    <div class="card-body p-md-5">
                        <div class="row justify-content-center">


                                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4" style="font-family: Arial, Helvetica, sans-serif;">Register Here</p>
                                <div class="container">
                                    <div class="row">
                                        <div class="col-4"></div>
                                        <div class="col-4">
                                            {%if messages%}
                                            {%for m in messages%}
                                            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                                <strong>Holy guacamole!</strong> {{m}}
                                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                                        aria-label="Close"></button>
                                            </div>
                                            {%endfor%}
                                            {%endif%}
                                        </div>
                                        <div class="col-4">

                                        </div>
                                    </div>
                                </div>

                                <div class="container">
                                    <div class="row">
                                        <div class="col-4"></div>
                                        <div class="col-4">
                                            <form action="" method="post" enctype="multipart/form-data">
                                                {%csrf_token%}
                                                {{form.as_p}}

                                                <div class="d-grid">
                                                    <button class="btn btn-primary btn-login text-uppercase fw-bold" type="submit">submit</button>
                                                </div>
                                                </form>
                                            </form>
                                        </div>
                                        <div class="col-4"></div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

    </div>
</section>


</body>
</html>